### ISSUE TITLE
404 redirect works differently in the Netlify production environment and the dev environment

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/inverted-wordles#7]
## Describe the bug

When a requested URL don't resolve to a static file, the site 404 page (404.html) is expected to show. This works well with Netlify hosted sites as the auto 404 redirect is supported by default (see [Custom 404 page handling](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling)).

However, when running `netlify dev` to start the site locally, the auto 404 redirect does not work. An unfriendly error page shows with a message "cannot get {page-url}".

### To reproduce
1. Access a non-existent endpoint in the production site, for example, https://inverted-wordles.netlify.app/wrong
2. The 404 page shows properly;
3. Run "netlify dev" locally;
4. Access a non-existent endpoint of the local site;
5. An unfriendly error page shows with a message "cannot get {page-url}".

### Expected behavior
The 404 page should show when accessing a non-existent endpoint of the local site.

## Screenshots
<img width="590" alt="error" src="https://user-images.githubusercontent.com/572877/120683607-d809d580-c46b-11eb-96ce-ee744197ef8b.png">

**Comment by greatislander** [comment]
@cindyli I can help with this— I'll leave a more full comment after my co-design session this afternoon.

**Comment by cindyli** [comment]
@amb26 did some research and the discussion can be found [here](https://matrix.to/#/!JcoHDrfLedPQdFhAXn:matrix.org/$qKCkKXfi1FGmEmt6Sy2pE42TslXT-L0LRkw40nQulII?via=matrix.org).

**Comment by greatislander** [comment]
Netlify Dev proxies Eleventy running in `--serve` mode. You can get Eleventy to show the 404 page in this context with the BrowserSync middleware shown here: https://www.11ty.dev/docs/quicktips/not-found/#with-serve (may need adjustments for your configuration).

**Comment by greatislander** [comment]
(I saw the conversation in Matrix but wasn't clear what redirect configuration you were trying— however, I know this solution will work as it's the recommended solution for handling 404s in local development.)

**Comment by cindyli** [comment]
> Netlify Dev proxies Eleventy running in `--serve` mode. You can get Eleventy to show the 404 page in this context with the BrowserSync middleware shown here: https://www.11ty.dev/docs/quicktips/not-found/#with-serve (may need adjustments for your configuration).

Thanks for the documentation, @greatislander. It helps. My experiment with this solution shows it solves the 404 redirect when starting the local site using `eleventy --serve` command. However, for sites started using `netlify dev`, the same issue persists.
